"""ORI Phase 4 - library.py: a small, curated oceanographic knowledge base.

Every entry is a CANDIDATE explanation - a documented, defensible reason two or more parameters
COULD move together - never a claim that it is what happened here. Matching is purely pattern-based
(parameter names + sign of relationship, taken from Phase 2 relational results); no LLM writes or
edits this file. Extend it by adding ProcessSpec entries, not by hand-writing text per dataset.

Signature convention: for a pairwise process, `signature` is (frozenset({param_a, param_b}), sign),
where sign is '+' if the two are expected to correlate positively and '-' if negatively - this makes
the match independent of which parameter Phase 2 happened to list first.
"""
from dataclasses import dataclass, field
from typing import FrozenSet, List, Optional, Tuple


@dataclass(frozen=True)
class ProcessSpec:
    key: str
    label: str
    domain: str                       # physical | chemical | biogeochemical
    description: str                  # neutral, textbook-level description of the candidate mechanism
    signature: Optional[Tuple[FrozenSet[str], str]] = None   # (parameter pair, expected sign) - None for combo/template specs
    requires: Tuple[str, ...] = field(default_factory=tuple)  # for combo specs: keys of the member specs that must all match
    note: Optional[str] = None


LIBRARY: List[ProcessSpec] = [
    ProcessSpec(
        key="bio_o2_consumption_n_cycle",
        label="Biological oxygen consumption linked to nitrogen cycling",
        domain="biogeochemical",
        signature=(frozenset({"nitrite", "DO"}), "-"),
        description=("Aerobic respiration, nitrification of ammonia to nitrite, and denitrification under low-oxygen "
                     "conditions are all processes in which elevated nitrite commonly co-occurs with reduced dissolved "
                     "oxygen. This is a general biogeochemical pattern, not specific to any one of the three processes."),
    ),
    ProcessSpec(
        key="respiration_linked_acidification",
        label="Respiration-linked acidification",
        domain="biogeochemical",
        signature=(frozenset({"pH", "nitrite"}), "-"),
        description=("Aerobic respiration and organic-matter degradation release CO2, which lowers pH, while the same "
                     "processes regenerate dissolved inorganic nitrogen (including nitrite). Lower pH co-occurring with "
                     "higher nitrite is a textbook signature of enhanced organic-matter breakdown, among other causes."),
    ),
    ProcessSpec(
        key="coupled_n_cycle_o2_ph",
        label="Coupled nitrogen-cycling / oxygen-consumption / acidification signature",
        domain="biogeochemical",
        requires=("bio_o2_consumption_n_cycle", "respiration_linked_acidification"),
        description=("When elevated nitrite co-occurs with BOTH reduced oxygen and reduced pH, the three findings are "
                     "consistent with the same underlying process (respiration / organic-matter remineralization / "
                     "nitrogen cycling) rather than being three unrelated coincidences - though this is still a "
                     "candidate reading of the pattern, not a distinct, separately confirmed mechanism."),
    ),
    ProcessSpec(
        key="nutrient_coregeneration",
        label="Co-regeneration of dissolved nutrients from organic/siliceous material",
        domain="biogeochemical",
        signature=(frozenset({"phosphate", "silicate"}), "+"),
        description=("Phosphate and silicate are regenerated by different pathways (organic-matter remineralisation for "
                     "phosphate; dissolution of biogenic silica for silicate), but both pathways are commonly enhanced "
                     "together in areas of higher productivity, terrestrial input, or accumulated organic/siliceous "
                     "material, which can produce a positive correlation between the two even though the release "
                     "mechanisms differ."),
    ),
    ProcessSpec(
        key="conservative_mixing_gradient",
        label="Conservative mixing / water-mass gradient",
        domain="physical",
        signature=(frozenset({"salinity", "temperature"}), "+"),
        description=("Salinity and temperature commonly covary across a spatial gradient where two water masses of "
                     "different origin mix conservatively - for example a coastal/freshwater-influenced end-member "
                     "versus an open-water end-member, or a shallow versus a deeper-influenced water column. A positive "
                     "or negative correlation between the two, especially one that tracks station position, is a classic "
                     "signature of such a gradient rather than of any single chemical process."),
    ),
    ProcessSpec(
        key="salinity_phosphate_positive_link",
        label="Higher-salinity water carrying a higher phosphate load",
        domain="physical",
        signature=(frozenset({"salinity", "phosphate"}), "+"),
        description=("A positive correlation between salinity and phosphate (rather than the more commonly cited "
                     "freshwater-dilution pattern, where lower salinity carries higher nutrients) is consistent with an "
                     "intrusion of higher-salinity subsurface or offshore water that is also nutrient-enriched, for "
                     "example through upwelling or vertical mixing bringing nutrient-rich water into the sampled layer."),
    ),
    ProcessSpec(
        key="salinity_do_negative_link",
        label="Higher-salinity water associated with lower oxygen",
        domain="physical",
        signature=(frozenset({"salinity", "DO"}), "-"),
        description=("Higher-salinity water carrying lower dissolved oxygen can indicate a subsurface or offshore "
                     "water mass with reduced ventilation reaching the sampled layer, or simply reflects both "
                     "parameters varying along the same spatial gradient as other water-mass indicators."),
    ),
    ProcessSpec(
        key="phosphate_do_negative_link",
        label="Elevated phosphate associated with lower oxygen",
        domain="biogeochemical",
        signature=(frozenset({"phosphate", "DO"}), "-"),
        description=("Elevated phosphate together with reduced oxygen is consistent with either an upwelled, "
                     "nutrient-rich, lower-oxygen water mass, or with biological oxygen consumption accompanying "
                     "the regeneration of phosphate from organic matter - the two are not distinguished by this "
                     "correlation alone."),
    ),
    ProcessSpec(
        key="temperature_do_solubility_link",
        label="Temperature-dependent oxygen solubility",
        domain="physical",
        signature=(frozenset({"temperature", "DO"}), "-"),
        description=("Warmer water holds less dissolved oxygen at saturation, a direct physical solubility effect "
                     "independent of any biological process. A negative correlation between temperature and "
                     "dissolved oxygen is one of the most well-established relationships in coastal oceanography."),
    ),
    ProcessSpec(
        key="upwelling_influenced_water",
        label="Combined higher-salinity / higher-phosphate / lower-oxygen signature",
        domain="physical",
        requires=("salinity_phosphate_positive_link", "salinity_do_negative_link", "phosphate_do_negative_link"),
        description=("Higher salinity, higher phosphate and lower oxygen occurring together across the same stations "
                     "is a combination commonly associated with the influence of upwelled or subsurface water "
                     "reaching the sampled layer, which characteristically carries this combination of properties. "
                     "This is one candidate reading of the combined pattern, not a confirmed water-mass identification."),
    ),
]

BY_KEY = {p.key: p for p in LIBRARY}
